### ISSUE TITLE
Square root of a Fraction?

### ISSUE THREAD

**Issue by MadsKirkFoged** [danm-de/Fractions#12]
Have a Square root function for a Fraction ever been on the table?
I need it from time to time.

Im guessing that it needs to be done in an iterative process and it might not be a easy as it sounds.
I could start working on it for this package if it would be accepted?

**Comment by danm-de** [comment]
Hi, 

The reason there is no square-root function is simple: "I haven't needed it before". I think this feature would be a good addition to `Fractions`.

I (hope that I) have made the data type as efficient and fast as possible. That's why there are two methods to convert `double -> Fraction`. Looking at https://en.wikipedia.org/wiki/Methods_of_computing_square_roots I think the 'Heron' variant seems to be the most promising. Guess it would require some kind of 'max number of iterations' (precision) to prevent infinite loops.

**Comment by MadsKirkFoged** [comment]
Sounds good that there is a simple reason for it not being there!

If you want to create it yourself that will be fine by me :-)
else I might take a look at it at a later time in the future.

**Comment by danm-de** [comment]
As I said earlier, I do not need it. Go ahead :-)

Am 8. Februar 2022 15:29:49 MEZ schrieb MadsKirkFoged ***@***.***>:
>Sounds good that there is a simple reason for it not being there!
>
>If you want to create it yourself that will be fine by me :-)
>else I might take a look at it at a later time in the future.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/danm-de/Fractions/issues/12#issuecomment-1032670698
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by danm-de** [comment]
Pull request https://github.com/danm-de/Fractions/pull/13 merged, Nuget packages updated. Thanks for your contribution!
