### ISSUE TITLE
Fractions.DLL showing as Malware / Virus

### ISSUE THREAD

**Issue by kaddrison** [danm-de/Fractions#86]
https://www.virustotal.com/gui/file/cb38cd5aa5a8c422d1373ec9de0053cbd22882952d129e7df0dea93100deb52f?nocache=1 any ideas how to stop this - AV is removing it

**Comment by danm-de** [comment]
One of my colleagues just checked the [latest version 8.0.3](https://www.nuget.org/packages/Fractions/8.0.3) (8.0.3):

- lib/net8.0/Fractions.dll: https://www.virustotal.com/gui/file/5c3cc677d7cac0f39717417391e624777effe688ce819f3a50ae8cfee2a0dfeb?nocache=1
- lib/netstandard2.0/Fractions.dll: https://www.virustotal.com/gui/file-analysis/MDQ0ZTFkY2JlMTFmM2NjOTY2NDc3ZTUyODM1YWVhNDI6MTcyNDA2MDQxOA==
- lib/netstandard2.1/Fractions.dll: https://www.virustotal.com/gui/file-analysis/MDQ1MDIwZDg5NmQ0YjM5N2E0MjI3YzZmZjJlYTVhZWU6MTcyNDA2MDMxNw==

(no issues found)

The [old version](https://www.nuget.org/packages/Fractions/4.0.1) (4.0.1), that you have posted has no issues:

- lib/net45/Fractions.dll: https://www.virustotal.com/gui/file/c7b8b74b8ec206d7c8deead27b27950f685d98c839b26de8a98fed8d2b478edb/details
- lib/netstandard1.1/Fractions.dll: https://www.virustotal.com/gui/file/4181c9c30e8ce94bb8d0cd1f8a9db35db431b6863d746a028acb960f8dd62947

I'm assuming you downloaded software from an untrustworthy website. The DLL has been replaced or infected with malware. The signature of the DLL can be forged because - as with most open source projects - there is a dummy license/key in the [source folder](https://github.com/danm-de/Fractions/blob/master/Fractions.snk).

The bad guy didn't try too hard either - he even used a DEBUG version of the assembly (and VC++ instead of the dotnet-compiler).

Your file:
![Screenshot from 2024-08-19 11-53-48](https://github.com/user-attachments/assets/4bfe0036-ccdc-49c8-b683-a607dde2ffd8)

The original DLL from nuget.org:
![Screenshot from 2024-08-19 12-00-43](https://github.com/user-attachments/assets/e1d9da06-1aa7-4ca5-94e5-483932b5ab27)
